import copy

# This recipe will insert a single protein into a bilayer membrane
protein = \
{1: {"gromacs": "pdb2gmx",
     "options": {"src": "proteinhis.pdb",
                 "tgt": "proteinopls.pdb",
                 "top": "protein.top"}},
 2: {"command": "set_itp",
     "options": {"src": "protein.top",
                 "tgt": "protein.itp"}},
 3: {"gromacs": "editconf",
     "options": {"src": "proteinopls.pdb",
                 "tgt": "proteinopls.pdb",
                 "dist": ""}},
 4: {"command": "set_prot_size",
     "options": {"src": "proteinopls.pdb",
                 "dir": "xy"}},
 5: {"command": "set_popc",
     "options": {"src": "x4bilayer.pdb",
                 "tgt": "popc.pdb"}},
 6: {"command": "set_nanom"},
 7: {"gromacs": "editconf",
     "options": {"src": "proteinopls.pdb",
                 "tgt": "proteinopls.pdb",
                 "box": "",
                 "angles": ["90", "90", "120"],
                 "bt": "tric"}},
 8: {"gromacs": "editconf",
     "options": {"src": "popc.pdb",
                 "tgt": "popc.pdb",
                 "box": ""}},
 9: {"command": "make_topol"},
10: {"gromacs": "editconf",
     "options": {"src": "proteinopls.pdb",
                 "tgt": "proteinopls.pdb",
                 "translate": ["0", "0", "0"]}},
11: {"gromacs": "genbox",
     "options": {"cp": "proteinopls.pdb",
                 "cs": "popc.pdb",
                 "tgt": "protpopc.pdb",
                 "top": "topol.top"}},
12: {"command": "make_water",
     "options": {"tgt": "water.pdb"}},
13: {"gromacs": "editconf",
     "options": {"src": "water.pdb",
                 "tgt": "water.pdb",
                 "box": ""}},
14: {"gromacs": "editconf",
     "options": {"src": "protpopc.pdb",
                 "tgt": "protpopc.pdb",
                 "box": "",
                 "angles": ["90", "90", "120"],
                 "bt": "tric"}},
15: {"gromacs": "genbox",
     "options": {"cp": "protpopc.pdb",
                 "cs": "water.pdb",
                 "tgt": "tmp.pdb",
                 "top": "topol.top"}},
16: {"command": "count_lipids"},
17: {"command": "make_topol"},
18: {"command": "make_topol_lipids"},
19: {"command": "make_steep"},
20: {"gromacs": "grompp",
     "options": {"src": "steep.mdp",
                 "src2": "tmp.pdb",
                 "tgt": "topol.tpr",
                 "top": "topol.top"}},
21: {"gromacs": "trjconv",
     "options": {"src": "tmp.mdp",
                 "src2": "topol.tpr",
                 "tgt": "tmp.pdb",
                 "pbc": "mol"}},
22: {"gromacs": "genion",
     "options": {"src": "topol.tpr",
                 "src2": "topol.top",
                 "tgt": "output.pdb",#<------------
                 "np": "",
                 "nn": ""}},
23: {"gromacs": "grompp",
     "options": {"src": "steep.mdp",
                 "src2": "output.pdb",#<------------
                 "tgt": "topol.tpr",
                 "top": "topol.top"}},
24: {"gromacs": "trjconv",
     "options": {"src": "output.pdb",#<------------
                 "src2": "topol.tpr",
                 "tgt": "output.pdb",#<------------
                 "trans": ["0", "0", "0"],
                 "pbc": "mol"}},
25: {"gromacs": "grompp",
     "options": {"src": "steep.mdp",
                 "src2": "output.pdb",
                 "tgt": "output.tpr", #<------------
                 "top": "topol.top"}},
26: {"gromacs": "trjconv",
     "options": {"src": "output.pdb",
                 "src2": "output.tpr",
                 "tgt": "hexagon.pdb",
                 "ur": "compact",
                 "pbc": "mol"}}
}

# This recipe modifies the previous one taking a ligand into account

protein_ligand = copy.copy(protein)

protein_ligand[9] = \
[{1: {"gromacs": "make_ndx",
      "options": {"src": "",
                  "tgt": "ligand_ha.ndx",
                  "ligand": True}},
 2: {"gromacs": "genrestr",
     "options": {"src": "",
                 "tgt": "posre_lig.itp",
                 "index": "lig_ha.ndx",
                 "forces": ["1000, 1000, 1000"],
                 "ligand": True}},
 3: {"command": "make_topol",
     "options": {"ligand": True}}}]
protein_ligand[17] = \
 {"command": "make_topol",
  "options": {"ligand": True}}
